---
title: "Energy outputs per technology"
output: html_document
---

```{r, echo=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=5, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
#PLOT ELECTRICITY OUTPUT OF TECHNOLOGIES PER HOUR

library(openxlsx)
library(reshape)
library(ggplot2)

data = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_conversion.xlsx","Output_energy_electricity")
data_stor = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_storage.xlsx","Storage_output_energy")
data_stor <- data.frame(data_stor$Elec)
colnames(data_stor) <- c("Storage")
data <- cbind(data,data_stor)
data_melted <- melt(data, id=c("X1"))

#plot per hour
ggplot(data_melted,aes(x=X1,y=value,fill=variable)) + geom_bar(stat = "identity") +
  labs(title="Electricity supplied per technology (hourly)",x="Hour", y="Energy supplied (kWh)", legend.title="Technology") +
  theme(legend.title = element_blank())

rm(list=ls(all=TRUE))
```

```{r, echo=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=5, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
#PLOT HEAT OUTPUT OF TECHNOLOGIES PER HOUR

library(openxlsx)
library(reshape)
library(ggplot2)

data = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_conversion.xlsx","Output_energy_heat")
data_stor = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_storage.xlsx","Storage_output_energy")
data_stor <- data.frame(data_stor$Heat)
colnames(data_stor) <- c("Storage")
data <- cbind(data,data_stor)
data_melted <- melt(data, id=c("X1"))

#plot per hour
ggplot(data_melted,aes(x=X1,y=value,fill=variable)) + geom_bar(stat = "identity") +
  labs(title="Heat supplied per technology (hourly)",x="Hour", y="Energy supplied (kWh)") +
  theme(legend.title = element_blank())

rm(list=ls(all=TRUE))

```

```{r, echo=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=5, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
#PLOT ELECTRICITY OUTPUT OF TECHNOLOGIES PER WEEK

library(openxlsx)
library(reshape)
library(ggplot2)
library(sqldf)

hrs_in_wk = 7 * 24
wks_in_yr = round((8760 / (24 * 7)))
t <- data.frame()
for(i in 1:wks_in_yr) {
  j = list(rep(i,hrs_in_wk))
  t <- rbind(t,j)
}
t[8737:8760,] = 53
row.names(t) = NULL
colnames(t) = c('weeks')

data = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_conversion.xlsx","Output_energy_electricity")
data_stor = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_storage.xlsx","Storage_output_energy")
data_stor <- data.frame(data_stor$Elec)
colnames(data_stor) <- c("Storage")
data <- cbind(data,data_stor)
data <- cbind(t,data)
data_m <- melt(data, id=c('weeks','X1'))
data_summed <- sqldf('select weeks, variable, sum(value) as value from data_m group by weeks,variable order by weeks')
ggplot(data_summed,aes(x=weeks,y=value,fill=variable)) + geom_bar(stat = "identity") +
  labs(title="Electricity supplied per technology (weekly)",x="Week", y="Energy supplied (kWh)") +
  theme(legend.title = element_blank())

rm(list=ls(all=TRUE))
                      
```

```{r, echo=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=5, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
#PLOT HEAT OUTPUT OF TECHNOLOGIES PER WEEK

library(openxlsx)
library(reshape)
library(ggplot2)
library(sqldf)

hrs_in_wk = 7 * 24
wks_in_yr = round((8760 / (24 * 7)))
t <- data.frame()
for(i in 1:wks_in_yr) {
  j = list(rep(i,hrs_in_wk))
  t <- rbind(t,j)
}
t[8737:8760,] = 53
row.names(t) = NULL
colnames(t) = c('weeks')

data = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_conversion.xlsx","Output_energy_heat")
data_stor = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_storage.xlsx","Storage_output_energy")
data_stor <- data.frame(data_stor$Elec)
colnames(data_stor) <- c("Storage")
data <- cbind(data,data_stor)
data <- cbind(t,data)
data_m <- melt(data, id=c('weeks','X1'))
data_summed <- sqldf('select weeks, variable, sum(value) as value from data_m group by weeks,variable order by weeks')
ggplot(data_summed,aes(x=weeks,y=value,fill=variable)) + geom_bar(stat = "identity") +
  labs(title="Heat supplied per technology (weekly)",x="Week", y="Energy supplied (kWh)") +
  theme(legend.title = element_blank())

rm(list=ls(all=TRUE))
                      
```

```{r, echo=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=5, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
#PLOT ANNUAL ELECTRICITY OUTPUT OF TECHNOLOGIES

library(openxlsx)
library(reshape)
library(ggplot2)

data = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_conversion.xlsx","Output_energy_electricity")
data_stor = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_storage.xlsx","Storage_output_energy")
data_stor <- data.frame(data_stor$Elec)
colnames(data_stor) <- c("Storage")
data <- cbind(data,data_stor)
data_m <- melt(data, id=c("X1"))
data_summed <- sqldf('select variable, sum(value) as value from data_m group by variable')

blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )

ggplot(data_summed, aes(x="", y=value, fill=variable)) + geom_bar(width = 1, stat = "identity") + coord_polar("y", start=0) + 
  blank_theme + theme(axis.text.x=element_blank())  +
  labs(title="Total share of electricity supplied per technology") +
  theme(legend.title = element_blank())

rm(list=ls(all=TRUE))
```

```{r, echo=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=5, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
#PLOT ANNUAL HEAT OUTPUT OF TECHNOLOGIES

library(openxlsx)
library(reshape)
library(ggplot2)

data = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_conversion.xlsx","Output_energy_heat")
data_stor = read.xlsx("H:\\projects\\ModularEnergyHub\\aimms_model\\energy_hub\\results_storage.xlsx","Storage_output_energy")
data_stor <- data.frame(data_stor$Elec)
colnames(data_stor) <- c("Storage")
data <- cbind(data,data_stor)
data_m <- melt(data, id=c("X1"))
data_summed <- sqldf('select variable, sum(value) as value from data_m group by variable')

blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )

ggplot(data_summed, aes(x="", y=value, fill=variable)) + geom_bar(width = 1, stat = "identity") + coord_polar("y", start=0) + 
  blank_theme + theme(axis.text.x=element_blank())  +
  labs(title="Total share of heat supplied per technology") +
  theme(legend.title = element_blank())

rm(list=ls(all=TRUE))
```